name: products_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"





dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  flutter_rating_bar: ^4.0.1
  getwidget:
  bloc:
  flutter_bloc:
  cupertino_icons: ^1.0.2
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  hive_generator: 
  


  
  
  
  
  flutter_lints: ^2.0.0


flutter:
 
  uses-material-design: true

  assets:
    - assets/loading.gif
    - assets/products.json
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
