import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:hive/hive.dart';
import 'package:products_app/model/hive_product.dart';
import 'package:products_app/model/products.dart';

class Repository with ChangeNotifier {
  bool isfetched = false;

  Future<void> loadJson() async {
    String jsontext = '';

    // Loading from assets json file
    // this json was generated by dart code i have include the script in folder name  jsongenerator
    try {
      jsontext = await rootBundle.loadString('assets/products.json');
    } catch (e) {
      throw e;
    }
    // var jsontext = await rootBundle.loadString('assets/products.json');

    var jsondata = json.decode(jsontext);
    print(jsondata);
    var tempProduct = ProductList.fromJson(jsondata);

    //saving in hive database
    try {
      tempProduct.Products.forEach((element) async {
        var hiveProcduct = HiveProduct(
            ProductName: element.ProductName,
            productRating: element.productRating,
            productDescription: element.productDescription,
            productUrl: element.productUrl);
        await Hive.box('products').add(hiveProcduct);
      });
    } catch (e) {
      throw e;
    }

    isfetched = true;
  }
}
